build:
  image: plugins/drone-git
  commands:
    - true
publish:
  docker:
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: ciscocloud/mantl-kibana
    tag: edge
    file: kibana/Dockerfile
    when:
      branch: master
  docker:
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: ciscocloud/mantl-kibana
    tag:
      - $$TAG
      - latest
    file: kibana/Dockerfile
    when:
      event: tag
